Update wiremock-standalone.jar to version 2.35.0 from 2.6.0
wiremock/python-wiremock pull request #48
Opened 2023-04-12 17:14 UTC by KjeldSchmidt

This updates to a newer version of wiremock, with the primary goal of getting security audit tools to stop complaining about `python-wiremock`.

It does not change any implementation logic, it only replaces the jar and the two singular references in the code.

All tests, as run by `tox run -e testenv` pass. Coverage has not changed, since neither tests nor implementation have been changed.

The PR is rebased onto the current master.

I wasn't sure whether I should update the version number in the `VERSION`-file, so I erred on the side of caution and went with "no".

Let me know if there is anything else I should do for this PR to be accepted.

Many thanks!

2023-04-30 12:13 UTC, oleg-nenashev requested changes
Thanks! Definitely an update is needed. Also, I'd recommend updating documentation in the same pull request:

```
Customizing the WireMock server JAR file:
--
30 |  
31 | WireMockServer(jar_path='/my/secret/location/wiremock-standalone-2.0.0.jar')
```

Also, merge conflict would need to be resolved.

2023-05-05 08:46 UTC, KjeldSchmidt commented
The documentation version has also been updated, and the commits have been rebased onto the new structure.

2023-05-07 13:26 UTC, mikeywaites commented
@KjeldSchmidt thanks a lot for taking the time to open this pr.  We are picking up steam on wiremock development!

Could i ask that you rebase 1 last time.  I've just added a new example/ module to the code base which will serve as a real working example for documentation, but also as an e2e test suite of sort that i can use to test out new features.

Once this is rebased I will run the test suite and then we can look at releasing support for 2.6 officially.

2023-05-25 14:40 UTC, KjeldSchmidt commented
Hey there, sorry for the delay, I was unavailable lately.

I have rebased again, without changing or adding anything else - I think this is all you needed me to do for?

Best wishes!

2023-05-30 10:53 UTC, oleg-nenashev commented
Needs @mikeywaites

2023-06-06 05:44 UTC, merged